/*
 * keymap for a Datel adapater + US keyboard (not the normal keyboard)
 * not mapped:
 * 	printscreen / sysreq
 *	scroll lcok
 *	pause / break
 *	numlock
 *	windows key 1
 *	windows key 2
 *	windows menu key
 */

static unsigned char gamecube_keymap[] = {
	/* 00 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_HOME,      KEY_END,
	/* 08 */ KEY_PAGEUP,    KEY_PAGEDOWN, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* 10 */ KEY_A,         KEY_B,        KEY_C,          KEY_D,          KEY_E,         KEY_F,          KEY_G,         KEY_H,
	/* 18 */ KEY_I,         KEY_J,        KEY_K,          KEY_L,          KEY_M,         KEY_N,          KEY_O,         KEY_P,
	/* 20 */ KEY_Q,         KEY_R,        KEY_S,          KEY_T,          KEY_U,         KEY_V,          KEY_W,         KEY_X,
	/* 28 */ KEY_Y,         KEY_Z,        KEY_1,          KEY_2,          KEY_3,         KEY_4,          KEY_5,         KEY_6,
	/* 30 */ KEY_7,         KEY_8,        KEY_9,          KEY_0,          KEY_MINUS,     KEY_EQUAL,      KEY_BACKSLASH, KEY_APOSTROPHE,
	/* 38 */ KEY_LEFTBRACE, KEY_EQUAL,    KEY_KPASTERISK, KEY_RIGHTBRACE, KEY_COMMA,     KEY_DOT,        KEY_SLASH,     KEY_RESERVED,
	/* 40 */ KEY_F1,        KEY_F2,       KEY_F3,         KEY_F4,         KEY_F5,        KEY_F6,         KEY_F7,        KEY_F8,
	/* 48 */ KEY_F9,        KEY_F10,      KEY_F11,        KEY_F12,        KEY_ESC,       KEY_INSERT,     KEY_DELETE,    KEY_GRAVE,
	/* 50 */ KEY_BACKSPACE, KEY_TAB,      KEY_RESERVED,   KEY_CAPSLOCK,   KEY_LEFTSHIFT, KEY_RIGHTSHIFT, KEY_LEFTCTRL,  KEY_LEFTALT,
	/* 58 */ KEY_RESERVED,  KEY_SPACE,    KEY_RESERVED,   KEY_RESERVED,   KEY_LEFT,      KEY_DOWN,       KEY_UP,        KEY_RIGHT,
	/* 60 */ KEY_RESERVED,  KEY_ENTER,    KEY_RESERVED,   KEY_RESERVED,   KEY_SEMICOLON, KEY_KPPLUS,     KEY_RESERVED,  KEY_RESERVED,
	/* 68 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* 70 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* 78 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* 80 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* 88 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* 90 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* 98 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* a0 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* a8 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* b0 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* b8 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* c0 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* c8 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* d0 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* d8 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* e0 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* e8 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* f0 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,
	/* f8 */ KEY_RESERVED,  KEY_RESERVED, KEY_RESERVED,   KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED,   KEY_RESERVED,  KEY_RESERVED
};
